test:
  stage: test
  image: registry.gitlab.com/gitlab-org/herokuish:latest
  services:
  - postgres:latest
  before_script:
    - cp -R . /tmp/app
  script:
    - /bin/herokuish buildpack test
  only:
    - branches 